backend:
  name: git-gateway
media_folder: "/images"
collections:
  - name: "data"
    label: "Data"
    files:
      - name: "authenticlearningdata"
        label: "Authentic Learning Data"
        file: "data.json"
        fields:
          - { label: "Data", name: "data", widget: "NestedJsonEditor" }
